version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eShop
  app:
    build: .
    ports:
      - '3000:8080'
    depends_on:
      - db
