import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { CssBaseline, Typography } from "@mui/material";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>eCommerce Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <main>
        <NavBar />
        <Typography variant="h1" align="center">
          Home Page
        </Typography>
        <ul>
          <li>
            <Link href={"/products-list"}>Products List</Link>
          </li>
          <li>
            <Link href={"/cart"}>cart</Link>
          </li>
          <li>
            <Link href={"/auth"}>Login/Register</Link>
          </li>
        </ul>
      </main>
    </>
  );
}
